# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2efb449be5cdbee4bfb9cafe9f722fdf"
application_url = "https://bridal-interests-beginner-tsunami.trycloudflare.com"
embedded = true
name = "ShopSense"
handle = "shopsense"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bridal-interests-beginner-tsunami.trycloudflare.com/auth/callback",
  "https://bridal-interests-beginner-tsunami.trycloudflare.com/auth/shopify/callback",
  "https://bridal-interests-beginner-tsunami.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
